# Generated by Django 3.2.3 on 2021-05-23 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_rename_person_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Person',
        ),
    ]
