# Generated by Django 3.2.3 on 2021-05-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_rename_user_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='blood_group',
            new_name='bloodGroup',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
