# Generated by Django 3.2.3 on 2021-05-25 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_auto_20210525_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.CharField(max_length=300)),
                ('medicines', models.IntegerField(default=0)),
                ('membername', models.CharField(max_length=20)),
                ('givenDate', models.DateTimeField(default=datetime.datetime(2021, 5, 26, 0, 30, 47, 499246))),
            ],
        ),
    ]
