# Generated by Django 3.2.3 on 2021-05-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_remove_medicalrecord_givendate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='medicines',
            field=models.IntegerField(max_length=300),
        ),
    ]
